// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/transactions": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/transactions";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/transaction.tsx": {
    id: "routes/transaction";
    page: "/transactions";
  };
};